import { Box } from "@mui/system";
import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import CustomerList from "../components/customers/customer-list";
import SearchCustomer from "../components/customers/search-customer";
import { useSnackbar } from "../Store/snackbar-context";
import styles from "../styles/Home.module.css";
import { useHttpGet } from "./hooks/useHttpGet";

const Home: NextPage = (props) => {
  const [urlState, setUrlState] = React.useState("/read-customer");
  const { customerData } = useHttpGet(urlState);

  const loadCustomersHandler = React.useCallback(
    (url: string) => {
      setUrlState(url);
    },
    [setUrlState]
  );
  return (
    <div className={styles.container}>
      <Head>
        <title>Store App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Box sx={{ marginLeft: "210px" }}>
        <SearchCustomer onLoadCustomers={loadCustomersHandler} />
      </Box>
      <main className={styles.main}>
        <CustomerList data={customerData} />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;

// export async function getServerSideProps(context: any) {
//   const res = await fetch(`https://.../data`)
//   const data = await res.json()

//   return { props: { data: 1 } };
// }
